# Generated by Django 4.1.2 on 2022-10-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogdetailpage",
            name="editable_title",
            field=models.TextField(
                help_text="Max length 50. This is the title to be used on the frontend. White space and line breaks will show in designs.",
                max_length=50,
            ),
        ),
    ]
