# Generated by Django 4.1.2 on 2022-10-29 05:27

from django.db import migrations
import streams.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogdetailpage_editable_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogdetailpage",
            name="content",
            field=wagtail.fields.StreamField(
                [("text_block", streams.blocks.TextBlock())],
                default="",
                use_json_field=True,
            ),
            preserve_default=False,
        ),
    ]
