# Generated by Django 4.1.2 on 2022-11-02 16:05

from django.db import migrations
import streams.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogdetailpage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogdetailpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("text_block", streams.blocks.TextBlock()),
                    (
                        "full_width_image",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    streams.blocks.ImageChooserBlock(
                                        help_text="Use an image of 1280px x 720px"
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional caption, max length = 40 characters",
                                        max_length=40,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
