# Generated by Django 4.1.2 on 2022-11-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_blogdetailpage_options_blogauthororderable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogindexpage",
            options={"verbose_name": "Blog List Page"},
        ),
    ]
