# Generated by Django 4.1.2 on 2022-11-02 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0077_alter_revision_user"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffmember",
            name="id",
        ),
        migrations.AddField(
            model_name="staffmember",
            name="page_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="wagtailcore.page",
            ),
            preserve_default=False,
        ),
    ]
