# Generated by Django 4.1.2 on 2022-11-02 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        ("wagtailimages", "0024_index_image_file_hash"),
        ("staff", "0002_remove_staffmember_id_staffmember_page_ptr"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffListPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "editable_title",
                    models.TextField(
                        help_text="Max length 50. This is the title to be used on the frontend. White space and line breaks will show in designs.",
                        max_length=50,
                    ),
                ),
                ("intro", models.TextField(max_length=250)),
                (
                    "top_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog List Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
