# Generated by Django 4.1.2 on 2022-11-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Max length is 100 characters", max_length=100
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Slugs should be all lower case separated by hypens. Must be unique . Must be unique",
                        max_length=150,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
