# Generated by Django 4.1.2 on 2022-11-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentcategory",
            name="slug",
            field=models.SlugField(
                help_text="Max length is 150. Slugs should be all lower case separated by hypens. Must be unique.",
                max_length=150,
                unique=True,
            ),
        ),
    ]
