# Generated by Django 4.1.2 on 2022-11-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0002_alter_contentcategory_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Content Category",
                "verbose_name_plural": "Content Categories",
            },
        ),
    ]
